export const NAV_LINKS = [
  { label: "Services", href: "/services" },
  // { label: "Case Studies", href: "/case-studies" },
  { label: "Schedule", href: "/schedule" },
];

export const SERVICES = [
  {
    id: "leads",
    title: "Lead Capture & Instant Response",
    short: "24/7 instant response to every lead — before your competitor even checks their phone.",
    problem: "A lead comes in at 8pm. You see it at 7am. They already called your competitor and booked. You lost $3,000 in revenue while you slept. Studies show that responding to a lead within 5 minutes makes you 21x more likely to close the deal — but the average trades business takes 6+ hours. Every hour of delay is money walking out the door.",
    solution: "Every lead from your website, Google, or ads gets an instant text and email response, automatic qualification, and a booking link — 24/7, even nights and weekends.",
    metric: "10-second response time",
    icon: "Phone",
    steps: [
      "Lead comes in from any source — website form, Google Ads, Facebook, Angi, Thumbtack, or a missed call",
      "System instantly sends a personalized text and email with your business name, acknowledging the request",
      "Lead is auto-qualified based on job type, location, and urgency — high-value jobs get flagged immediately",
      "Booking link is included so they can schedule on the spot — no phone tag required",
      "You and your team get a real-time notification with all the details, ready to follow up if needed",
    ],
    features: [
      "Instant text + email response (under 10 seconds)",
      "Works 24/7 — nights, weekends, holidays",
      "Captures leads from website, Google, Facebook, Angi, Thumbtack",
      "Auto-qualifies by job type, location, and budget",
      "Self-service booking link in every response",
      "Real-time notifications to you and your team",
      "Missed call text-back automation",
      "Integrates with your existing CRM or field service software",
    ],
    example: "A plumbing company was losing 3-4 leads per week because their response time averaged 4+ hours. After deploying lead capture automation, every lead got a personalized text within 8 seconds. In the first month, they booked 11 additional jobs they would have lost — worth over $14,000 in revenue.",
    roi: "$3,000–$15,000/year in recovered revenue from leads that would have gone to competitors",
  },
  {
    id: "followups",
    title: "Estimate Follow-Up Engine",
    short: "Automated follow-ups that turn sent quotes into signed jobs.",
    problem: "You send the estimate. Then... nothing. No follow-up. The homeowner goes with whoever calls back first. 60% of your quotes die in silence. You're not losing jobs because your prices are too high — you're losing them because you didn't follow up. The average homeowner gets 3 quotes. The company that stays in touch wins the job.",
    solution: "Automated, personalized follow-up sequences after every estimate — texts, emails, and reminders on a smart schedule until they book or say no.",
    metric: "3x quote close rate",
    icon: "Zap",
    steps: [
      "You send an estimate through your normal process — email, text, paper, whatever you already use",
      "System logs the estimate and starts a follow-up sequence tailored to the job size and type",
      "Day 1: personalized text checking if they have questions about the estimate",
      "Day 3: email with a clear call-to-action to approve and schedule the work",
      "Day 7: friendly reminder text — 'Just wanted to make sure this didn't get buried'",
      "Day 14: final follow-up with a limited-time incentive or simply asking for a yes or no",
      "If they respond at any point, the sequence pauses and you take over the conversation",
    ],
    features: [
      "Automated text + email sequences after every estimate",
      "Smart timing based on job type and value",
      "Personalized with customer name, job details, and your business name",
      "Auto-pauses when the customer responds",
      "Escalation alerts for high-value jobs that go cold",
      "Dashboard showing which estimates are open, responded, or lost",
      "Works alongside your existing quoting process",
      "Customizable message templates in your brand voice",
    ],
    example: "An HVAC company sent 40+ estimates per month but only followed up on about half — and usually just once. After deploying the follow-up engine, their quote-to-close rate jumped from 28% to 47%. That's 8 extra jobs per month at an average of $2,800 each — $22,400 in monthly revenue they were leaving on the table.",
    roi: "$5,000–$25,000/year in revenue from estimates that would have died in silence",
  },
  {
    id: "scheduling",
    title: "Smart Scheduling & Dispatch",
    short: "Automated booking, reminders, and dispatch — no more phone tag.",
    problem: "Your office manager spends 2+ hours a day on phone tag, rescheduling, and coordinating crews. That's $15,000/year in wasted salary. Meanwhile, customers are frustrated because they can't book easily, they forget their appointments, and your crews are driving back and forth across town because nobody optimized the route.",
    solution: "Automated online booking, rescheduling, appointment reminders, and route-optimized dispatch — all synced to your calendar and crew schedules.",
    metric: "15+ hours saved weekly",
    icon: "Calendar",
    steps: [
      "Customer selects an available time slot through your website or booking link — no phone call needed",
      "Confirmation text + email sent instantly with job details and address",
      "Automated reminders at 24 hours and 2 hours before the appointment",
      "If the customer needs to reschedule, they do it themselves through the link — no phone tag",
      "Your crew gets dispatch notifications with job details, customer info, and optimized route",
      "After the job, the system triggers the next step — invoice, review request, or follow-up",
    ],
    features: [
      "Online self-service booking (no phone calls required)",
      "Automated confirmation texts + emails",
      "24-hour and 2-hour appointment reminders",
      "Self-service rescheduling for customers",
      "Crew dispatch notifications with job details",
      "Route optimization to reduce drive time",
      "Calendar sync with Google Calendar, Outlook, or field service software",
      "No-show tracking and automatic re-booking prompts",
      "Capacity management — never overbook your crews",
    ],
    example: "A landscaping company's office manager was spending 12+ hours per week coordinating schedules by phone. After deploying smart scheduling, 70% of bookings happened online without a single call. Appointment no-shows dropped from 15% to 3% thanks to automated reminders. The office manager now spends that time on sales instead of phone tag.",
    roi: "$12,000–$20,000/year in saved labor + reduced no-shows and windshield time",
  },
  {
    id: "reviews",
    title: "Review & Reputation Autopilot",
    short: "5-star reviews on autopilot after every completed job.",
    problem: "You finish the job, shake hands, and leave. Nobody asks for a review. Your competitor has 200+ Google reviews and you have 12. Homeowners check reviews before they call — 93% of consumers say online reviews influence their buying decisions. If you're invisible on Google, you're invisible to your next customer.",
    solution: "Automated review request after every completed job. Filters unhappy customers to private feedback first, routes happy ones straight to Google.",
    metric: "5x review volume",
    icon: "Star",
    steps: [
      "Job is marked complete in your system (or you mark it manually — one tap)",
      "Customer receives a branded text: 'How was your experience with [Your Company]?'",
      "If they rate 4-5 stars: they get a direct link to leave a Google review with one tap",
      "If they rate 1-3 stars: they get routed to a private feedback form so you can fix the issue before it goes public",
      "You get notified of every response — so you can thank happy customers and address unhappy ones fast",
      "Monthly report shows review count, average rating, and sentiment trends",
    ],
    features: [
      "Automated review request after every completed job",
      "Smart sentiment routing — happy → Google, unhappy → private feedback",
      "One-tap Google review link (no friction for the customer)",
      "Branded messages with your company name and logo",
      "Works via text and email for maximum reach",
      "Private feedback alerts so you can resolve issues before they go public",
      "Monthly reputation report with rating trends",
      "Supports Google, Yelp, and Facebook reviews",
      "Customizable timing — send immediately or delay by hours",
    ],
    example: "An electrical contractor had 18 Google reviews after 6 years in business. After 4 months on the Review Autopilot, they had 140+ reviews with a 4.9 average. They moved from page 3 to the top 3 in Google Maps for their area. Inbound leads increased 35% — directly tied to their improved visibility.",
    roi: "$8,000–$30,000/year in new business from improved Google visibility and trust",
  },
  {
    id: "pipeline",
    title: "CRM & Pipeline Automation",
    short: "Every lead, estimate, and job tracked in one place — automatically.",
    problem: "Customer info in your phone, quotes in email, schedule on a whiteboard. Nothing talks to anything. You're the bottleneck. When someone on your team asks 'Did we follow up with the Johnson job?' nobody knows the answer. Leads slip through the cracks. Invoices get sent late. Customers feel forgotten.",
    solution: "Unified pipeline: lead → estimate → job → invoice → follow-up, all automated and tracked in one place. No more manual data entry.",
    metric: "Zero leads lost",
    icon: "LineChart",
    steps: [
      "Every new lead is automatically logged with source, contact info, and job details",
      "When you send an estimate, the pipeline stage updates automatically",
      "Approved estimates automatically create a scheduled job with all the details",
      "Job completion triggers invoice generation and sends it to the customer",
      "After payment, the system triggers a review request and adds them to your customer database",
      "Past customers get periodic check-ins for maintenance, seasonal offers, or referral requests",
    ],
    features: [
      "Automatic lead logging from all sources",
      "Visual pipeline: lead → estimate → job → invoice → complete",
      "Stage transitions happen automatically — no manual updates",
      "Customer history in one place (every call, email, job, and payment)",
      "Automatic invoice generation on job completion",
      "Past customer re-engagement sequences",
      "Team visibility — everyone sees the same pipeline",
      "Works with or replaces your existing CRM",
      "Reporting dashboard with close rates, revenue, and pipeline health",
      "Integrates with QuickBooks, Stripe, and field service tools",
    ],
    example: "A GC running 3 crews had customer data scattered across texts, emails, and sticky notes. After implementing CRM automation, every lead was tracked from first contact to final payment. They discovered they'd been losing 20% of leads to poor handoffs between office and field. Within 2 months, they recovered $8,000/month in revenue just from leads that used to fall through the cracks.",
    roi: "$10,000–$40,000/year in recovered revenue from better pipeline visibility and zero dropped leads",
  },
  {
    id: "custom",
    title: "Custom Workflow Builder",
    short: "We find the task eating your week and automate it.",
    problem: "Every business has that one repetitive task eating 5+ hours a week — vendor emails, invoicing, reporting, inventory updates, permit applications, crew timesheets. You've thought about hiring someone to handle it, but it's not enough work for a full-time person and it's too tedious for your top people.",
    solution: "We identify your biggest time sinks and build custom automations tailored to your business. Invoicing, reporting, vendor coordination — whatever's eating your week.",
    metric: "40+ hours saved monthly",
    icon: "Wrench",
    steps: [
      "We audit your operations and identify the tasks that consume the most time relative to their value",
      "You pick the biggest pain point — the thing you'd automate tomorrow if you could",
      "We design a custom automation tailored to how your business actually works (not how software thinks it should work)",
      "We build, test, and deploy it — usually live within 2 weeks",
      "We monitor, maintain, and optimize it monthly — and build the next one when you're ready",
    ],
    features: [
      "Custom-built for your specific workflows (not templates)",
      "Automated invoicing and payment collection",
      "Vendor email and PO generation",
      "Daily/weekly/monthly report automation",
      "Crew timesheet and payroll prep",
      "Inventory and supply reorder alerts",
      "Customer communication sequences",
      "Data sync between disconnected tools",
      "Document generation (contracts, change orders, lien waivers)",
      "Whatever repetitive task is eating your week — we can automate it",
    ],
    example: "A painting contractor spent 6 hours every Friday preparing crew timesheets, generating invoices, and sending weekly reports to clients. We automated all three: timesheets pull from the scheduling system, invoices generate and send automatically on job completion, and client reports compile and email themselves every Monday morning. The owner got his Fridays back.",
    roi: "$15,000–$40,000/year in saved labor from eliminating repetitive manual work",
  },
];

export const PROCESS_STEPS = [
  {
    step: "Step 1",
    title: "Audit",
    desc: "We dig into your operations for free. Every call flow, every follow-up, every scheduling headache. You get a report showing exactly where you're bleeding money and what to fix first.",
    icon: "Search",
  },
  {
    step: "Step 2",
    title: "Build",
    desc: "We build and deploy custom automations for your business. No templates. No generic software. Real systems, live in weeks — built around how you actually work.",
    icon: "Zap",
  },
  {
    step: "Step 3",
    title: "Scale",
    desc: "We maintain everything, optimize monthly, and prove ROI with hard numbers in your Performance Report. You focus on running crews and closing jobs.",
    icon: "TrendingUp",
  },
];

export const FAQ_ITEMS = [
  {
    q: "How is this different from ServiceTitan / Jobber / Housecall Pro?",
    a: "We don't replace your field service software — we supercharge it. Those tools are great for managing jobs, but they don't respond to leads at 2am, follow up on unsold estimates, or get you more Google reviews. We plug into whatever you already use and automate the gaps.",
  },
  {
    q: "What if the system makes a mistake?",
    a: "Our systems use strict safety guardrails. They never send a message, book a job, or take action without following your rules. If something falls outside the norm, it escalates to you or your office manager for approval. You stay in control.",
  },
  {
    q: "How quickly will I see results?",
    a: "Most clients see their first automation live within 2 weeks. By the end of Month 1, you'll have a complete diagnostic and your first systems deployed. By Month 3, your core operations are running tighter than you thought possible.",
  },
  {
    q: "What tools do you integrate with?",
    a: "ServiceTitan, Jobber, Housecall Pro, QuickBooks, Google Business Profile, Google Calendar, Stripe, Angi, Thumbtack, Yelp, Facebook, and more. If it has an API, we can connect it.",
  },
  {
    q: "What happens if I want to cancel?",
    a: "No long-term contracts. Cancel anytime with 30 days notice. Everything we built stays yours. We'll document it so your next hire or office manager can maintain it.",
  },
  {
    q: "Is my data safe?",
    a: "Absolutely. Your data is strictly isolated with enterprise-grade security. We never share client data with third parties. Your customer info, job data, and business operations stay in your silo. Period.",
  },
  {
    q: "What's the 40-hour guarantee?",
    a: "On our Growth and Partner tiers, if we don't prove we saved you at least 40 hours of manual labor in our Monthly Performance Report, your next month is free. We put our money where our mouth is.",
  },
  {
    q: "What's included in the free website?",
    a: "Every new client gets a professionally designed, mobile-optimized website built and hosted at no extra cost. It's not a template — we custom-build it for your brand, optimized for local SEO and lead capture. It's our way of making sure you look as sharp online as your operations run behind the scenes.",
  },
];

export const CASE_STUDIES = [
  {
    industry: "HVAC Services",
    company: "Regional HVAC Company",
    revenue: "$580k/year",
    problem: "Lead response time was 6+ hours. Office manager manually copied leads from website forms into their scheduling system. Lost 3-4 jobs per week to faster competitors.",
    solution: "Built automated lead capture → instant response → qualification → booking pipeline. Every lead gets a text in under 10 seconds with availability and a booking link.",
    metrics: {
      hoursSaved: 45,
      responseTime: { before: "6+ hours", after: "10 seconds" },
      satisfaction: { before: "72%", after: "94%" },
      monthlySavings: 4200,
    },
    quote: "We went from losing leads overnight to booking jobs before our competitors even check their email.",
  },
  {
    industry: "Plumbing",
    company: "Family Plumbing Company",
    revenue: "$420k/year",
    problem: "Sent 30+ estimates per month but never followed up. Owner estimated 60% of quotes died in silence because nobody called back.",
    solution: "Deployed automated estimate follow-up sequences — personalized texts and emails at day 1, 3, 7, and 14 after every quote. Smart escalation for high-value jobs.",
    metrics: {
      hoursSaved: 38,
      responseTime: { before: "Never", after: "Same day" },
      satisfaction: { before: "3.2/5", after: "4.8/5" },
      monthlySavings: 5200,
    },
    quote: "We were leaving $60k a year on the table just from not following up. Now it happens automatically.",
  },
  {
    industry: "Landscaping",
    company: "Growing Landscape Company",
    revenue: "$340k/year",
    problem: "Only had 14 Google reviews after 8 years in business. Competitors with 200+ reviews were winning all the search traffic and homeowner trust.",
    solution: "Automated review request system triggered after every completed job. Happy customers get a direct Google review link. Unhappy customers get routed to private feedback first.",
    metrics: {
      hoursSaved: 12,
      responseTime: { before: "N/A", after: "Same day" },
      satisfaction: { before: "14 reviews", after: "120+ reviews" },
      monthlySavings: 3800,
    },
    quote: "We went from 14 reviews to over 120 in four months. Now we show up first on Google and the phone rings itself.",
  },
];

export const TRUST_POINTS = [
  {
    icon: "Shield",
    title: "Built-in Safety Checks",
    desc: "Our systems never send a message, book a job, or take action without following your rules. When something's unusual, it escalates to you.",
  },
  {
    icon: "Lock",
    title: "Your Data Stays Yours",
    desc: "Strict enterprise-grade security. Your customer data and business info is isolated. We never share client data with third parties.",
  },
  {
    icon: "LineChart",
    title: "Provable ROI",
    desc: "Monthly Performance Reports show the exact hours saved and dollars returned. No vanity metrics — just real numbers.",
  },
  {
    icon: "Rocket",
    title: "Done For You",
    desc: "We don't hand you software and wish you luck. We build it, run it, maintain it, and prove it works — every month.",
  },
];

export const INTEGRATIONS = [
  "ServiceTitan", "Jobber", "Housecall Pro", "QuickBooks",
  "Google Business", "Google Calendar", "Stripe", "Angi",
  "Thumbtack", "Yelp", "Facebook", "Zapier",
];
